### PR TITLE
Add meshify node

### PR DESCRIPTION
**Pull request by BastienCagna**
Automatic generation of gifti mesh file from a volumic nifti image

### CODE REVIEW

**Comment by BastienCagna** [comment]
I'd just convert the test script to a node without any testing
@davidmeunier79 do you have any idea of how to install slam on the setup? Are we force to wait for the release?

**Review by davidmeunier79 — CHANGES_REQUESTED** [review]
Salut @BastienCagna ; code look great to me.

**Comment by davidmeunier79** [comment]
> I'd just convert the test script to a node without any testing
> @davidmeunier79 do you have any idea of how to install slam on the setup? Are we force to wait for the release?

Re @BastienCagna , it seems your code is failiing because the installation requires scikit-image  instead of skimage.
Also, is there a way to add a unitest for this node?

**Comment by BastienCagna** [comment]
Ok, thanks. I'm gonna modify it!

**Comment by BastienCagna** [comment]
Still some setup problems but it comes from slam setup.py. I fixed it up and submitted a PR.
I tryed to add a test that test the node with a fake image created temporary

**Comment by davidmeunier79** [comment]
Ok @BastienCagna let us know it goes with PR on slam; 
Also please remove all files in .idea (or add it in the .gitignore)

**Comment by BastienCagna** [comment]
@davidmeunier79 I think it's ready to merge! (with a rebase?)

**Review by davidmeunier79 — APPROVED** [review]

**Comment by davidmeunier79** [comment]
Merci @BastienCagna

**Comment by davidmeunier79** [comment]
I have done a squash and merge, unclear to me if it is cleaner in the commit history this way, but the rebase would have been a mess as I did a PR in between

**Pull request merged**
